steps:
- name: node
  entrypoint: npm
  args: ["run", "create-env"]
  env:
  - 'DB_URI=${_DB_URI}'
  - 'DISCORD_ENDPOINT=${_DISCORD_ENDPOINT}'
  - 'TURINGTEST=${_TURINGTEST}'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy']
timeout: '1600s'